apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30001
      protocol: TCP
      name: mongo
  type: NodePort